name: hot-air-balloon

services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-galaxy_universal}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql

  migrate:
    build:
      context: .
    command: ["alembic", "upgrade", "head"]
    environment:
      APP_ENVIRONMENT: local
      APP_DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-1234}@database:5432/${POSTGRES_DB:-galaxy_universal}
    depends_on:
      database:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  api:
    build:
      context: .
    environment:
      APP_ENVIRONMENT: local
      APP_DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-1234}@database:5432/${POSTGRES_DB:-galaxy_universal}
      APP_LOG_JSON: "true"
      APP_TRUSTED_HOSTS: '["localhost","127.0.0.1"]'
    depends_on:
      migrate:
        condition: service_completed_successfully
    init: true
    ports:
      - "${APP_PORT:-8000}:8000"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped
    stop_grace_period: 30s

  kafka:
    image: apache/kafka:3.9.0
    container_name: fastapi-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
  kafka-data: