"""add more fields for auditing functionality

Revision ID: 614cdcb6a43f
Revises: c4bedcc4ef78
Create Date: 2026-08-06 13:56:37.879309
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '614cdcb6a43f'
down_revision: str | None = 'c4bedcc4ef78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column(
        'users', 
        sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('source_system', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'source_system')
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###