"""create assistant tool audit and trace events

Revision ID: 9c66222c34c7
Revises: 20260818_0003
Create Date: 2026-08-18 11:26:39.225886
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9c66222c34c7'
down_revision: str | None = '20260818_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_tool_audit_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_tool_audit_records'))
    )
    op.create_index(op.f('ix_assistant_tool_audit_records_actor'), 'assistant_tool_audit_records', ['actor'], unique=False)
    op.create_index(op.f('ix_assistant_tool_audit_records_decision'), 'assistant_tool_audit_records', ['decision'], unique=False)
    op.create_index(op.f('ix_assistant_tool_audit_records_tool_name'), 'assistant_tool_audit_records', ['tool_name'], unique=False)
    op.create_table('assistant_tool_trace_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_tool_trace_events'))
    )
    op.create_index(op.f('ix_assistant_tool_trace_events_actor'), 'assistant_tool_trace_events', ['actor'], unique=False)
    op.create_index(op.f('ix_assistant_tool_trace_events_event'), 'assistant_tool_trace_events', ['event'], unique=False)
    op.create_index(op.f('ix_assistant_tool_trace_events_tool_name'), 'assistant_tool_trace_events', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_tool_trace_events_tool_name'), table_name='assistant_tool_trace_events')
    op.drop_index(op.f('ix_assistant_tool_trace_events_event'), table_name='assistant_tool_trace_events')
    op.drop_index(op.f('ix_assistant_tool_trace_events_actor'), table_name='assistant_tool_trace_events')
    op.drop_table('assistant_tool_trace_events')
    op.drop_index(op.f('ix_assistant_tool_audit_records_tool_name'), table_name='assistant_tool_audit_records')
    op.drop_index(op.f('ix_assistant_tool_audit_records_decision'), table_name='assistant_tool_audit_records')
    op.drop_index(op.f('ix_assistant_tool_audit_records_actor'), table_name='assistant_tool_audit_records')
    op.drop_table('assistant_tool_audit_records')
    # ### end Alembic commands ###