"""create documents and outbox

Revision ID: c4bedcc4ef78
Revises: 20260801_0001
Create Date: 2026-08-04 10:56:31.664449
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c4bedcc4ef78'
down_revision: str | None = '20260801_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=256), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False),
    sa.Column('blob_container', sa.String(length=128), nullable=False),
    sa.Column('blob_name', sa.String(length=1024), nullable=False),
    sa.Column('blob_url', sa.Text(), nullable=False),
    sa.Column('blob_etag', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_documents_idempotency_key'))
    )
    op.create_index(op.f('ix_documents_sha256_hex'), 'documents', ['sha256_hex'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index(op.f('ix_outbox_created_at'), 'outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_topic'), 'outbox', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_topic'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_created_at'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_documents_sha256_hex'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###