"""add manufacturing maintenance tables

Revision ID: d38fb5db49a1
Revises: 614cdcb6a43f
Create Date: 2026-08-10 14:18:16.164164
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd38fb5db49a1'
down_revision: str | None = '614cdcb6a43f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plant_type', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites'))
    )
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_assets_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_code'), 'assets', ['code'], unique=True)
    op.create_index(op.f('ix_assets_site_id'), 'assets', ['site_id'], unique=False)
    op.create_table('spare_parts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=False),
    sa.Column('on_hand_qty', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_spare_parts_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spare_parts'))
    )
    op.create_index(op.f('ix_spare_parts_code'), 'spare_parts', ['code'], unique=True)
    op.create_index(op.f('ix_spare_parts_site_id'), 'spare_parts', ['site_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_work_orders_asset_id_assets')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_work_orders_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders'))
    )
    op.create_index(op.f('ix_work_orders_asset_id'), 'work_orders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_work_orders_code'), 'work_orders', ['code'], unique=True)
    op.create_index(op.f('ix_work_orders_site_id'), 'work_orders', ['site_id'], unique=False)
    op.create_table('work_order_spare_parts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('spare_part_id', sa.Uuid(), nullable=False),
    sa.Column('required_qty', sa.Integer(), nullable=False),
    sa.Column('consumed_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], name=op.f('fk_work_order_spare_parts_spare_part_id_spare_parts')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_spare_parts_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_spare_parts'))
    )
    op.create_index(op.f('ix_work_order_spare_parts_spare_part_id'), 'work_order_spare_parts', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_work_order_spare_parts_work_order_id'), 'work_order_spare_parts', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_spare_parts_work_order_id'), table_name='work_order_spare_parts')
    op.drop_index(op.f('ix_work_order_spare_parts_spare_part_id'), table_name='work_order_spare_parts')
    op.drop_table('work_order_spare_parts')
    op.drop_index(op.f('ix_work_orders_site_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_code'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_asset_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_spare_parts_site_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_code'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_assets_site_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###